services:
  docker_service:
    build:
      context: .
      args:
        PACK : docker
    tty: true  
  docker-compose_service:
    build:
      context: .
      args:
        PACK : docker-compose
    tty: true    